---
title: "Volleyball"
output: html_document
date: "2024-09-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Volleyball Z-Scores Analysis

```{r}
library(tidyverse)
```

## load data 
```{r}
gamedata <- read_csv("https://raw.githubusercontent.com/dwillis/NCAAWomensVolleyballData/main/data/ncaa_womens_volleyball_matchstats_2024.csv")
```

## team averages 
```{r}
perset <- gamedata |> 
  mutate(
    digsperset= digs/s,
    assistsperset= assists/s,
    killsperset = kills/s,
    acesperset = aces/s
  ) |>
  select(team, date, digsperset, assistsperset, acesperset, killsperset)
```

## Create a Z-Score 
```{r}
teamszscore <- perset |>
  group_by(team) |> 
  mutate(
    killzscore = as.numeric(scale(killsperset, center = TRUE, scale = TRUE)),
    digszscore = as.numeric(scale(digsperset, center = TRUE, scale = TRUE)),
    assistszscore = as.numeric(scale(assistsperset, center = TRUE, scale = TRUE)), 
    aceszscore = as.numeric(scale(acesperset, center = TRUE, scale = TRUE)),
    TotalZscore =killzscore + digszscore + aceszscore + assistszscore
  ) |> ungroup() 

```

## arrange 
```{r}
teamszscore |> arrange(desc(TotalZscore))

```

## finding maryland data 
```{r}
teamszscore |> filter(team == "Maryland")
```

```{r}
### analysis 
###What is shown is that Maryland ranks very low compared to the other teams Z-Score analysis. From these games the top Z-score is 8, the Z-Score of Maryland best game was 3.7, according to these metrics. This shows, that the team needs some more in all these areas. Another team that looks like Maryland is Northern Arizona, Although they did have a good game that had a Z-score of 5, there other games reflect Maryland's as well. A story that could be here is the exploration of a team winning performance for example when Maryland does well in digs, assists, kills and aces does that account to winning? 

```

```{r}
## Arkansas Pine Bluff Volleyball team has had a awful start to their season with a record of 2-14, however they're still at the top of averages for the most in digs this season.

## Arkansas Pine Bluff averages 25.75% in digs the most in the NCAA, however this stat doesn't necessarily determine if the team is good. Pine Bluff stats shows that they're primarily always put on defense, a good potential factor to why there dig average is so high. In volleyball digs are important but to what degree? Arkansas Pine Bluff shows that one can get digs a lot but because they are forced too, not just because it's apart of the game. When a team is constantly hammered by the team's offense, that can force the other team to have more digs. 

#Just because Arkansas Pine Bluff could get digs were those good digs? and did this help them win? Looking at their offensive stats, their kill percentage is only 14.75%, which isn't high for a game that goes to 25. Arkansas Pine Bluff may be good in defense, but their offense is lacking and their record is a reflection of this. 
```

